#!/bin/sh
mvn package
rm -rf ../natives-sdk
mkdir -p ../natives-sdk
# script that installs the build to the local Maven repo
cp sdk-install ../natives-sdk/
cp target/gabien-natives-0.666-SNAPSHOT.jar ../natives-sdk/natives.jar
cp ../COPYING.txt ../natives-sdk/
cp ../CREDITS.txt ../natives-sdk/

