#!/bin/sh
# gabien-common - Cross-platform game and UI framework
# Written starting in 2016 by contributors (see CREDITS.txt)
# To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
# A copy of the Unlicense should have been supplied as COPYING.txt in this repository. Alternatively, you can find it at <https://unlicense.org/>.

if [ "$#" -ne 1 ]; then
 echo "sdk-rel RELEASE_ID"
 exit 1
fi

echo "-- GaBIEn Natives Release Build --"

export UNA_BUILD_ID="$1"

./sdk-make || exit

rm -rf ../natives-sdk ../natives-sdk.zip || exit
mkdir -p ../natives-sdk || exit
# script that installs the build to the local Maven repo
cp sdk-install ../natives-sdk/ || exit
cp sdk-install.cmd ../natives-sdk/ || exit
cp natives.jar ../natives-sdk/natives.jar || exit
cp ../COPYING.txt ../natives-sdk/ || exit
cp ../CREDITS.txt ../natives-sdk/ || exit
cp README.md ../natives-sdk/ || exit
cd ../natives-sdk || exit
../natives/ktsz * > ../natives-sdk.zip || exit

