#!/bin/sh
# gabien-common - Cross-platform game and UI framework
# Written starting in 2016 by contributors (see CREDITS.txt)
# To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
# A copy of the Unlicense should have been supplied as COPYING.txt in this repository. Alternatively, you can find it at <https://unlicense.org/>.

# tested using Zig 0.11.0-dev.2892+fd6200eda

. ./sdk-clean

set -e

mkdir -p $LIBUNA

if [ "$UNA_BUILD_ID" = "" ]; then
 echo "const char una_version[] = \"`date +%Y.%m.%d.%H.%M.%S`\";" > c/version.c
else
 echo "const char una_version[] = \"$UNA_BUILD_ID\";" > c/version.c
fi

COMMONFLAGS="-Wno-attributes -Ofast -shared"
TARGETS_U="i386-linux-gnu x86_64-linux-gnu aarch64-linux-gnu riscv64-linux-gnu"
TARGETS_M="x86_64-macos aarch64-macos"
SOURCES="c/version.c c/badgpu_jni.c c/loader_jni.c c/vorbis_jni.c c/mp3_jni.c c/badgpu/badgpu.c c/badgpu/badgpu_gl.c c/badgpu/badgpu_glbind.c c/badgpu/badgpu_sw.c c/badgpu/badgpu_swtnl.c c/badgpu/badgpu_swclip.c c/badgpu/badgpu_swrop.c c/badgpu/badgpu_tce.c c/badgpu/badgpu_dl.c c/badgpu/badgpu_wsi_egl.c"
SOURCES_U="c/badgpu/badgpu_wsi_zzz.c"
SOURCES_W="c/badgpu/badgpu_wsi_wgl.c"
SOURCES_M="c/badgpu/badgpu_wsi_cgl.c"

# Tools & etc.
ZIG=thirdparty/zig/zig
CLANG="clang"
# in theory, we shouldn't be using API level 9 libraries, but you need to use those to get access to ANativeWindow_fromSurface in the NDK.
# assume it's a packaging error or something. if it isn't, then it isn't.
NDK_PLATFORM9=thirdparty/android-ndk-r9d/platforms/android-9
NDK_PLATFORM21=thirdparty/android-ndk-r12b/platforms/android-21
NDK_ARM_GCC=thirdparty/android-ndk-r9d/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc
NDK_MIPS_GCC=thirdparty/android-ndk-r9d/toolchains/mipsel-linux-android-4.6/prebuilt/linux-x86_64/bin/mipsel-linux-android-gcc
NDK_X86_GCC=thirdparty/android-ndk-r9d/toolchains/x86-4.6/prebuilt/linux-x86_64/bin/i686-linux-android-gcc
NDK_AARCH64_GCC=thirdparty/android-ndk-r12b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc
NDK_X86_64_GCC=thirdparty/android-ndk-r12b/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin/x86_64-linux-android-gcc

# Continue...

for TARGET in $TARGETS_U ; do
 echo $TARGET generic-unix
 "$CLANG" -target $TARGET -fPIC -flto $SOURCES $SOURCES_U -o $LIBUNA/natives.$TARGET $COMMONFLAGS -nostdlib -nostdlibinc -fuse-ld=lld -isystem c/generic-unix-libc
done

if [ "$GABIEN_NATIVES_SKIP_MAW" = "" ]; then
 # LTO not yet supported
 for TARGET in $TARGETS_M ; do
  echo $TARGET macish
  "$ZIG" cc -target $TARGET $SOURCES $SOURCES_M -o $LIBUNA/natives.$TARGET $COMMONFLAGS
  # "$CLANG" -target $TARGET -fPIC -flto $SOURCES $SOURCES_M -o $LIBUNA/natives.$TARGET $COMMONFLAGS -nostdlib -nostdlibinc -fuse-ld=lld -isystem c/generic-unix-libc thirdparty/zig/lib/libc/darwin/libSystem.tbd -Wl,-platform_version,macos,11.0.0,128
 done
else
 echo macish SKIPPED
fi
# ideally, would do 32-bit RISC-V, but I had errors with Zig and I can't figure out which ABI to use, so nope
# ideally, would do the BSDs, but no libc and can't override
# Windows with style
doMinGWW64Build() {
 if [ "$GABIEN_NATIVES_SKIP_MAW" = "" ]; then
  echo $1 mingw-w64
  $2-gcc -Wno-psabi -flto $SOURCES $SOURCES_W -o $LIBUNA/natives.$1 $COMMONFLAGS -lgdi32 -lopengl32 -Wl,--kill-at
  $2-strip $LIBUNA/natives.$1
 else
  echo $1 mingw-w64 SKIPPED
 fi
}
doMinGWW64Build x86-windows-gnu i686-w64-mingw32
doMinGWW64Build x86_64-windows-gnu x86_64-w64-mingw32
# ANDROID IS REALLY REALLY WEIRD
echo THE ANDROID BUILDS
doAndroidBuild() {
 if [ "$GABIEN_NATIVES_SKIP_MAW" = "" ]; then
  echo $1 android-ndk
  $2 -Wno-psabi -DANDROID $SOURCES $SOURCES_U c/android_jni.c -o $LIBUNA/natives.$1 $COMMONFLAGS --sysroot $3 -ldl -lm -llog -landroid -lEGL -lGLESv1_CM
 else
  echo $1 android-ndk SKIPPED
 fi
}
doAndroidBuild arm-linux-android     $NDK_ARM_GCC     $NDK_PLATFORM9/arch-arm
doAndroidBuild mipsel-linux-android  $NDK_MIPS_GCC    $NDK_PLATFORM9/arch-mips
doAndroidBuild x86-linux-android     $NDK_X86_GCC     $NDK_PLATFORM9/arch-x86
doAndroidBuild aarch64-linux-android $NDK_AARCH64_GCC $NDK_PLATFORM21/arch-arm64
doAndroidBuild x86_64-linux-android  $NDK_X86_64_GCC  $NDK_PLATFORM21/arch-x86_64
echo THE ANDROID BUILDS ARE OVER NOW
rm -f $LIBUNA/*.lib
rm -f $LIBUNA/*.pdb
# strip anything we can
for x in `ls $LIBUNA` ; do
 llvm-strip $LIBUNA/$x || true
done

# Fake Maven metadata
mkdir -p src/main/resources/META-INF/maven/t20kdc.hs2/gabien-natives
cp pom.xml src/main/resources/META-INF/maven/t20kdc.hs2/gabien-natives/pom.xml

# Licensing files ; these are stored in the JAR so that they are always shipped even when umvn pulls the JAR out of the natives-sdk release (a gloriously evil technique engineered by our most cackly witch)
mkdir -p src/main/resources/assets/gabien/licensing/stb_vorbis
mkdir -p src/main/resources/assets/gabien/licensing/minimp3
mkdir -p src/main/resources/assets/gabien/licensing/common
cp ../thirdparty/stb_vorbis_modified/COPYING.txt src/main/resources/assets/gabien/licensing/stb_vorbis/COPYING.txt
cp ../thirdparty/stb_vorbis_modified/CREDITS.txt src/main/resources/assets/gabien/licensing/stb_vorbis/CREDITS.txt
cp ../thirdparty/minimp3_modified/LICENSE src/main/resources/assets/gabien/licensing/minimp3/LICENSE
cp ../COPYING.txt src/main/resources/assets/gabien/licensing/common/COPYING.txt
cp ../CREDITS.txt src/main/resources/assets/gabien/licensing/common/CREDITS.txt

# Update umvn
cp ../micromvn/umvn.class ./

# Create natives.jar
rm -f natives.jar
java umvn install -q
cp target/gabien-natives-0.666-SNAPSHOT.jar natives.jar


echo
echo "Build ID: $UNA_BUILD_ID"
echo "sha256sum: `sha256sum natives.jar`"
echo "content sums..."
sha256sum $LIBUNA/*
echo

