#!/bin/sh
mvn package
rm -rf ../una-sdk
mkdir -p ../una-sdk
# script that installs the UNA build to the local Maven repo
cp sdk-install ../una-sdk/
cp target/gabien-una-0.666-SNAPSHOT.jar ../una-sdk/una.jar
cp ../COPYING.txt ../una-sdk/
cp ../CREDITS.txt ../una-sdk/

