#!/bin/sh
if [ -e natives.jar ]; then
 mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=natives.jar
else
 mvn org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file -Dfile=../natives-sdk/natives.jar
fi

