#!/bin/sh
# gabien-common - Cross-platform game and UI framework
# Written starting in 2016 by contributors (see CREDITS.txt)
# To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
# A copy of the Unlicense should have been supplied as COPYING.txt in this repository. Alternatively, you can find it at <https://unlicense.org/>.

SCRIPT_PATH="`readlink -e $0`"
SCRIPT_DIR="`dirname "$SCRIPT_PATH"`"
cd "$SCRIPT_DIR"
java umvn install:install-file -Dfile=natives.jar -DgroupId=t20kdc.hs2 -DartifactId=gabien-natives -Dversion=0.666-SNAPSHOT -Dpackaging=jar
