#!/bin/bash
set -e

# self build

./build-self

./make-scratch

# external comp.

cp umvn.class ../../c3ds-projects/

GABIEN_NATIVES_DEV=1 gabien-ready

pushd ../../gabien-app-r48
../gabien-common/micromvn/umvn package
popd

pushd ../../c3ds-projects/natsue
./build.sh
popd

pushd ../natives-util
# :(
GABIEN_NATIVES_DEV=1 JAVA_1_8_HOME="C:\Program Files\Eclipse Adoptium\jdk-8.0.442.6-hotspot" wine ../micromvn/umvn.cmd test
popd
