#!/bin/bash
set -e

# activate!
. ../bin/activate

# self build

./build-self

./make-scratch

# external comp.

cp umvn.class ../../c3ds-projects/

echo "-- gabien-do ready --"

pushd ..
GABIEN_NATIVES_DEV=1 gabien-do ready
popd

echo "-- r48 smoke test --"

pushd ../../gabien-app-r48
../gabien-common/micromvn/umvn package
popd

echo "-- natsue --"

pushd ../../c3ds-projects/natsue
./build.sh
popd

echo "-- gabien natives --"

pushd ../natives-util
# :(
GABIEN_NATIVES_DEV=1 JAVA_1_8_HOME="$JAVA_1_8_HOME_W" wine ../micromvn/umvn.cmd test
popd
