; gabien-common - Cross-platform game and UI framework
; Written starting in 2016 by contributors (see CREDITS.txt)
; To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
; A copy of the Unlicense should have been supplied as COPYING.txt in this repository. Alternatively, you can find it at <https://unlicense.org/>.

; This would be a theme configuration file, but right now it's not much of one.
; Still, the border flags are saner now.
; Border flags are: moveDown, clear, tiled, lightBkg
(borderFlags 0 btn)
(borderFlags 0 btnP moveDown)
(borderFlags 0 label)
(borderFlags 0 textBox)
(borderFlags 0 textBoxF)
(borderFlags 0 window clear)
(borderFlags 0 sbTray tiled)
(borderFlags 0 sbNub tiled)
(borderFlags 0 tabA)
(borderFlags 0 tabB)
(borderFlags 0 tabSel)
(borderFlags 0 i11)
(borderFlags 0 i12)
(borderFlags 0 r48Overlay)

(borderFlags 1 btn tiled)
(borderFlags 1 btnP tiled moveDown)
(borderFlags 1 label tiled)
(borderFlags 1 textBox tiled)
(borderFlags 1 textBoxF tiled)
(borderFlags 1 window tiled)
(borderFlags 1 sbTray)
(borderFlags 1 sbNub tiled)
(borderFlags 1 tabA tiled)
(borderFlags 1 tabB tiled)
(borderFlags 1 tabSel tiled)
(borderFlags 1 i11 tiled)
(borderFlags 1 i12 tiled)
(borderFlags 1 r48Overlay)


(borderFlags 2 btn tiled lightBkg)
(borderFlags 2 btnP tiled moveDown lightBkg)
(borderFlags 2 label tiled lightBkg)
(borderFlags 2 textBox tiled lightBkg)
(borderFlags 2 textBoxF tiled lightBkg)
(borderFlags 2 window tiled lightBkg)
(borderFlags 2 sbTray lightBkg)
(borderFlags 2 sbNub tiled lightBkg)
(borderFlags 2 tabA tiled lightBkg)
(borderFlags 2 tabB tiled lightBkg)
(borderFlags 2 tabSel tiled lightBkg)
(borderFlags 2 i11 tiled lightBkg)
(borderFlags 2 i12 tiled lightBkg)
(borderFlags 2 r48Overlay)

(borderFlags 3 btn)
(borderFlags 3 btnP)
(borderFlags 3 label)
(borderFlags 3 textBox)
(borderFlags 3 textBoxF)
(borderFlags 3 window clear)
(borderFlags 3 sbTray tiled)
(borderFlags 3 sbNub tiled)
(borderFlags 3 tabA)
(borderFlags 3 tabB)
(borderFlags 3 tabSel)
(borderFlags 3 i11)
(borderFlags 3 i12)
(borderFlags 3 r48Overlay)

