; gabien-common - Cross-platform game and UI framework
; Written starting in 2016 by contributors (see CREDITS.txt)
; To the extent possible under law, the author(s) have dedicated all copyright and related and neighboring rights to this software to the public domain worldwide. This software is distributed without any warranty.
; A copy of the Unlicense should have been supplied as COPYING.txt in this repository. Alternatively, you can find it at <https://unlicense.org/>.

; This would be a theme configuration file, but right now it's not much of one.
; Still, the border flags are saner now.
; Border flags are: moveDown, clear, tiled, lightBkg
(id 0
	btn ()
	btnP (moveDown)
	label ()
	textBox ()
	textBoxF ()
	window (clear)
	sbTray (tiled)
	sbNub (tiled)
	tabA ()
	tabB ()
	tabSel ()
	i11 ()
	i12 ()
	r48Overlay ()
)

(id 1
	btn (tiled)
	btnP (tiled moveDown)
	label (tiled)
	textBox (tiled)
	textBoxF (tiled)
	window (tiled)
	sbTray ()
	sbNub (tiled)
	tabA (tiled)
	tabB (tiled)
	tabSel (tiled)
	i11 (tiled)
	i12 (tiled)
	r48Overlay ()
)

(id 2
	btn (tiled lightBkg)
	btnP (tiled moveDown lightBkg)
	label (tiled lightBkg)
	textBox (tiled lightBkg)
	textBoxF (tiled lightBkg)
	window (tiled lightBkg)
	sbTray (lightBkg)
	sbNub (tiled lightBkg)
	tabA (tiled lightBkg)
	tabB (tiled lightBkg)
	tabSel (tiled lightBkg)
	i11 (tiled lightBkg)
	i12 (tiled lightBkg)
	r48Overlay ()
)

(id 3
	btn ()
	btnP ()
	label ()
	textBox ()
	textBoxF ()
	window (clear)
	sbTray (tiled)
	sbNub (tiled)
	tabA ()
	tabB ()
	tabSel ()
	i11 ()
	i12 ()
	r48Overlay ()
)
