#!/bin/sh
lua specify.lua < badgpu.h > badgpu.md &&
pandoc badgpu.md -o badgpu.html &&
pandoc badgpu.md -o badgpu.pdf &&
gcc -g badgpu.c badgpu_glbind.c badgpu_tce.c badgpu_dl.c badgpu_wsi_egl.c badgputest.c -o badgputest -ldl &&
gcc -g badgpu_tce.c badgputest_tce.c -o badgputest_tce &&
i686-w64-mingw32-gcc -g badgpu.c badgpu_glbind.c badgpu_tce.c badgpu_dl.c badgpu_wsi_wgl.c badgputest.c -o badgputest.exe -lopengl32 -lgdi32 &&
i686-w64-mingw32-gcc -g badgpu.c badgpu_glbind.c badgpu_tce.c badgpu_dl.c badgpu_wsi_egl.c badgputest.c -o badgputest_egl.exe &&
./badgputest &&
qoiconv tmp.qoi tmp.png &&
qoiconv tmp2.qoi tmp2.png &&
./badgputest_tce
