[package]
name = "datum-rs"
version = "0.5.0"
description = "A portable, minimal S-expression format."
repository = "https://github.com/20kdc/gabien-common/"
license = "Unlicense"
edition = "2018"

[features]
default = ["std"]
std = ["alloc"]
alloc = []
